name: flutter_chat_ui_starter
description: A new Flutter project.


version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  simple_animations: ^1.1.3
  page_transition: ^1.1.7+6
  firebase_core: ^1.3.0
  firebase_analytics: ^8.0.3
  firebase_auth: ^1.0.2
  firebase_storage: ^8.0.5
  cloud_firestore: ^1.0.4
  provider: ^5.0.0
  timeago: ^3.0.2
  modal_progress_hud: ^0.1.3
  flutter_slidable: ^0.6.0
  auto_direction: ^0.0.5
  image_picker: ^0.7.5
  fluttertoast: ^8.0.7
  photo_view: ^0.5.0
  path_provider:
  flowder: ^0.2.0
  flutter_linkify: ^5.0.2
  url_launcher: ^6.0.4
  record: ^2.1.1
  audioplayers: 0.16.0
  flutter_document_picker: ^4.0.1
  permission: ^0.1.7
  system_settings: ^2.0.0
  dio: ^4.0.0
  firebase_messaging:
  flui: ^0.9.2
  clipboard: ^0.1.3
  flutter_easyloading: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter




flutter:


  uses-material-design: true

  assets:
   - assets/images/
   - assets/audio/

  fonts:
    - family: RobotoSlab
      fonts:
        - asset: fonts/RobotoSlab-VariableFont_wght.ttf
